application:
  name: any-application

kafka:
  bootstrap:
    server: "localhost:9092"
  topics:
    producer: the-target-topic
    consumer: topic-to-consume
client:
  my-app:
    hostname: "localhost:8080"

endpoints:
  health:
    enabled: true